jobs:
      
#MANIFESTS
      
  - name: extdopt-manifest1
    type: manifest
    steps:
      - IN: fl-image1
       # versionNumber: 100
      - IN: extdopt-tg1
    flags:
      - man_flextdpots
      
  - name: extdopt-manifest2multiimg
    type: manifest
    steps:
      - IN: fl-image2
      - IN: fl-image7workingdir
      - IN: flecs-dopts4
        applyTo:
          - fl-image2
      - IN: extdopt-tg2
      
  - name: extdopt-manifest3entrypt
    type: manifest
    steps:
      - IN: fl-image6entrypoint
      - IN: extdopt-tg3
      
  - name: extdopt-manifest4driftking
    type: manifest
    steps:
      - IN: fl-image7workingdir
      - IN: extdopt-tg4
      
#DEPLOYMENTS 

  - name: extdopt-ecsdeployup
    type: deploy
    steps:
      - IN: extdopt-manifest1
      - IN: fl-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: extdopt-tpdeployup
    type: deploy
    steps:
      - IN: extdopt-manifest2multiimg
      - IN: fltp-dopts2
      - IN: fl-tripubcluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: extdopt-ddcdeployep
    type: deploy
    steps:
      - IN: extdopt-manifest3entrypt
      - IN: extdopt-ddc1
      - IN: fl-ddccluster
        
  - name: extdopt-ddcdeploywd
    type: deploy
    steps:
      - IN: extdopt-manifest4driftking
      - IN: extdopt-ddc2
      - IN: fl-ddccluster
