triggers:
   - name: tpm-tg1
     type: trigger
     version:
       counter: 0
       
   - name: tpm-tg2
     type: trigger
     version:
       counter: 0
       
   - name: tpm-tg3
     type: trigger
     version:
       counter: 1
