triggers:
   - name: extdopt-tg1
     type: trigger
     version:
       counter: 0
       
   - name: extdopt-tg2
     type: trigger
     version:
       counter: 0
       
   - name: extdopt-tg3
     type: trigger
     version:
       counter: 0
