jobs:
  - name: fl-manifest1
    type: manifest
    steps:
      - IN: fl-image1

  - name: fl-manifest2multiimg
    type: manifest
    steps:
      - IN: fl-image2
      - IN: fl-image7workingdir
        applyTo:
          - fl-image2

  - name: fl-ecsdeploybg1
    type: deploy
    steps:
      - IN: fl-manifest1
      - IN: fl-manifest2multiimg
        switch: off
      - IN: fl-ecscluster

  - name: extdopt-manifest2multiimg
    type: manifest
    steps:
      - IN: fl-image2
      - IN: fl-image7workingdir
      - IN: extdoptecs-dopts5
        applyTo:
          - fl-image2
      - IN: extdopt-tg2
      
  - name: extdopt-ecsdeployept
    type: deploy
    steps:
      - IN: extdopt-manifest2multiimg
      - IN: fl-ecscluster
