jobs:
      
#MANIFESTS
      
  - name: extdopt-manifest1
    type: manifest
    steps:
      - IN: fl-image1
       # versionNumber: 100
      - IN: extdopt-tg1
    flags:
      - man_flextdpots
      
  - name: extdopt-manifest2multiimg
    type: manifest
    steps:
      - IN: fl-image2
      - IN: fl-image7workingdir
      - IN: flecs-dopts5
        applyTo:
          - fl-image2
      - IN: extdopt-tg2
      
  - name: extdopt-manifest3entrypt
    type: manifest
    steps:
      - IN: fl-image6entrypoint
      - IN: extdopt-tg3
      
  - name: extdopt-manifest4driftking
    type: manifest
    steps:
      - IN: fl-image7workingdir
      - IN: extdopt-tg4
      
#DEPLOYMENTS 

  - name: extdopt-ecsdeploywdir
    type: deploy
    steps:
      - IN: extdopt-manifest2multiimg
      - IN: fl-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: extdopt-ecsdeployept
    type: deploy
    steps:
      - IN: extdopt-manifest3entrypt
      - IN: flecs-dopts4
      - IN: fl-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
#   - name: extdopt-tpdeployept #First deploy something in tripub n copy conatiner name n give in fltp-dopts2 resource
#     type: deploy
#     steps:
#       - IN: extdopt-manifest3entrypt
#       - IN: fltp-dopts2
#       - IN: fl-tripubcluster
#       - TASK: managed
#         deployMethod: upgrade

  - name: extdopt-tpdeploywdir
    type: deploy
    steps:
      - IN: extdopt-manifest4driftking
      - IN: fltp-dopts1
      - IN: fl-tripubcluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: extdopt-ddcdeployept
    type: deploy
    steps:
      - IN: extdopt-manifest3entrypt
      - IN: extdopt-ddc1
      - IN: fl-ddccluster
        
#   - name: extdopt-ddcdeploywdir #First deploy something in ddc n copy conatiner name n give in extdopt-ddc2 resource
#     type: deploy
#     steps:
#       - IN: extdopt-manifest4driftking
#       - IN: extdopt-ddc2
#       - IN: fl-ddccluster
